//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apl.Entities.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.Roles = new HashSet<role>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Pass { get; set; }
        public string Phone { get; set; }
        public bool IsLocked { get; set; }
        public bool IsConnected { get; set; }
        public bool IsActive { get; set; }
        public short CountFailedPassAttempt { get; set; }
        public short CountAfterPassAttempt { get; set; }
        public Nullable<int> UserCreated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public Nullable<System.DateTime> DateLastLockout { get; set; }
        public Nullable<int> UserLastLockout { get; set; }
        public Nullable<System.DateTime> DateLastPassChange { get; set; }
        public Nullable<int> UserUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> UserResetPass { get; set; }
        public Nullable<System.DateTime> DateResetPass { get; set; }
        public string Cmnt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<role> Roles { get; set; }
    }
}
